In [24]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [25]:
df = pd.read_csv("ecommerce_churn.csv")

In [26]:
df.head

<bound method NDFrame.head of      customer_id   age  annual_income  tenure_months  monthly_spend  \
0           2001  34.0       470994.0           49.0        36974.0
1           2002  41.0       372922.0           14.0        25882.0
2           2003   NaN       143257.0           15.0        32210.0
3           2004  28.0       236419.0           31.0        28136.0
4           2005  27.0       394022.0            1.0        15709.0
..           ...   ...            ...            ...            ...
117         2118  45.0       210429.0            4.0        36972.0
118         2119  60.0       282206.0            4.0        34181.0
119         2120  21.0       324820.0           56.0         6944.0
120         2003   NaN       143257.0           15.0        32210.0
121         2100  60.0       412782.0           51.0        32476.0

     support_calls  orders_last_6_months contract_type         region  churn
0              1.0                   5.0       Monthly          Abuja      0
1              4.0                   4.0        Annual  Port Harcourt      0
2              4.0                   8.0     Quarterly          Lagos      0
3              5.0                  14.0     Quarterly          Lagos      0
4              3.0                   4.0       Monthly          lagos      0
..             ...                   ...           ...            ...    ...
117            5.0                   9.0       Monthly          Lagos      0
118            2.0                   4.0        Annual  Port Harcourt      0
119            1.0                   7.0     Quarterly          Lagos      0
120            4.0                   8.0     Quarterly          Lagos      0
121            0.0                  10.0       Monthly          LAGOS      0

[122 rows x 10 columns]>

In [27]:
df.describe().T 
#age,annual_income and monthly_spend have missing values
#age and support_calls have a negative value
#annual_income is 1.8m so it's a outlier

,count,mean,std,min,25%,50%,75%,max
customer_id,122.0,2060.352459,35.074165,2001.0,2030.25,2060.5,2090.75,2120.0
age,120.0,42.125000,12.183170,-4.0,33.75,44.0,52.00,60.0
annual_income,121.0,296888.859504,158707.300417,70000.0,229265.00,282206.0,336667.00,1800000.0
tenure_months,122.0,34.647541,21.332055,1.0,16.00,33.5,53.00,72.0
monthly_spend,121.0,29197.966942,9865.290437,6944.0,24018.00,30034.0,34866.00,51550.0
support_calls,122.0,3.073770,2.089597,-2.0,1.25,3.0,4.00,10.0
orders_last_6_months,122.0,7.754098,2.966233,1.0,6.00,8.0,10.00,16.0
churn,122.0,0.213115,0.411197,0.0,0.00,0.0,0.00,1.0

In [28]:
print("Shape: ", df.shape)

Shape:  (122, 10)

In [29]:
df.info

<bound method DataFrame.info of      customer_id   age  annual_income  tenure_months  monthly_spend  \
0           2001  34.0       470994.0           49.0        36974.0
1           2002  41.0       372922.0           14.0        25882.0
2           2003   NaN       143257.0           15.0        32210.0
3           2004  28.0       236419.0           31.0        28136.0
4           2005  27.0       394022.0            1.0        15709.0
..           ...   ...            ...            ...            ...
117         2118  45.0       210429.0            4.0        36972.0
118         2119  60.0       282206.0            4.0        34181.0
119         2120  21.0       324820.0           56.0         6944.0
120         2003   NaN       143257.0           15.0        32210.0
121         2100  60.0       412782.0           51.0        32476.0

     support_calls  orders_last_6_months contract_type         region  churn
0              1.0                   5.0       Monthly          Abuja      0
1              4.0                   4.0        Annual  Port Harcourt      0
2              4.0                   8.0     Quarterly          Lagos      0
3              5.0                  14.0     Quarterly          Lagos      0
4              3.0                   4.0       Monthly          lagos      0
..             ...                   ...           ...            ...    ...
117            5.0                   9.0       Monthly          Lagos      0
118            2.0                   4.0        Annual  Port Harcourt      0
119            1.0                   7.0     Quarterly          Lagos      0
120            4.0                   8.0     Quarterly          Lagos      0
121            0.0                  10.0       Monthly          LAGOS      0

[122 rows x 10 columns]>

In [30]:
df.isnull().sum().sort_values(ascending=False)

age                     2
annual_income           1
contract_type           1
monthly_spend           1
customer_id             0
tenure_months           0
support_calls           0
orders_last_6_months    0
region                  0
churn                   0
dtype: int64

In [31]:
missing = df.isnull().sum().sort_values(ascending=False)
missing_pct = (df.isnull().mean()*100).sort_values(ascending=False)

missing_report = pd.DataFrame({
    "missing_count" : missing,
    "missing_percent" : missing_pct.round(2)
})

missing_report

                      missing_count  missing_percent
age                               2             1.64
annual_income                     1             0.82
contract_type                     1             0.82
monthly_spend                     1             0.82
customer_id                       0             0.00
tenure_months                     0             0.00
support_calls                     0             0.00
orders_last_6_months              0             0.00
region                            0             0.00
churn                             0             0.00

In [32]:
for col in ["age", "annual_income", "monthly_spend"] :
    df[col] = df[col].fillna(df[col].median())

df["contract_type"] = df["contract_type"].fillna("unknown")
df.isnull().sum()

customer_id             0
age                     0
annual_income           0
tenure_months           0
monthly_spend           0
support_calls           0
orders_last_6_months    0
contract_type           0
region                  0
churn                   0
dtype: int64

In [33]:
print(df["region"].value_counts(dropna=False))

region
Lagos            35
Port Harcourt    27
Enugu            25
Abuja            18
Ibadan           11
lagos             2
LAGOS             2
ENUGU             1
enugu             1
Name: count, dtype: int64

In [34]:
df["region"] = (
    df["region"]
    .astype("string")
    .str.strip()
    .str.title()
)

df["region"].value_counts(dropna=False)

region
Lagos            39
Port Harcourt    27
Enugu            27
Abuja            18
Ibadan           11
Name: count, dtype: Int64

In [35]:
print("invalid ages: ")
display(df[df["age"]<0])

invalid ages:

,customer_id,age,annual_income,tenure_months,monthly_spend,support_calls,orders_last_6_months,contract_type,region,churn
10,2011,-4.0,70000.0,16.0,43146.0,3.0,7.0,Monthly,Lagos,1

In [36]:
print("invalid support_call counts: ")
display(df[df["support_calls"]<0])

invalid support_call counts:

,customer_id,age,annual_income,tenure_months,monthly_spend,support_calls,orders_last_6_months,contract_type,region,churn
74,2075,34.0,384230.0,34.0,44623.0,-2.0,11.0,Quarterly,Enugu,1

In [37]:
df.loc[df["age"] < 0, "age"] = np.nan #makes the age that's less than 0 an empty set 
df.loc[df["support_calls"] <0, "support_calls"] = np.nan #makes the support_call that's less than 0 an empty set 

df["age"] = df["age"].fillna(df["age"].median()) #filled the empty set with a median
df["support_calls"] = df["support_calls"].fillna(df["support_calls"].median())

df[["age", "support_calls"]].describe()

              age  support_calls
count  122.000000     122.000000
mean    42.549180       3.114754
std     11.326924       2.037649
min     21.000000       0.000000
25%     34.000000       2.000000
50%     44.000000       3.000000
75%     52.000000       4.000000
max     60.000000      10.000000

In [38]:
print(df["age"])

0      34.0
1      41.0
2      44.0
3      28.0
4      27.0
       ...
117    45.0
118    60.0
119    21.0
120    44.0
121    60.0
Name: age, Length: 122, dtype: float64

In [39]:
Q1 = df["annual_income"].quantile(0.25)
Q3 = df["annual_income"].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 - 1.5 * IQR

outliers = df[
    (df["annual_income"] < lower) |
    (df["annual_income"] > upper)
]

print("Lower bound:", lower)
print("Upper bound:", upper)

display(outliers)

Lower bound: 68404.875
Upper bound: 175698.125

,customer_id,age,annual_income,tenure_months,monthly_spend,support_calls,orders_last_6_months,contract_type,region,churn
0,2001,34.0,470994.0,49.0,36974.0,1.0,5.0,Monthly,Abuja,0
1,2002,41.0,372922.0,14.0,25882.0,4.0,4.0,Annual,Port Harcourt,0
3,2004,28.0,236419.0,31.0,28136.0,5.0,14.0,Quarterly,Lagos,0
4,2005,27.0,394022.0,1.0,15709.0,3.0,4.0,Monthly,Lagos,0
5,2006,34.0,216310.0,54.0,32537.0,4.0,8.0,Monthly,Lagos,0
...,...,...,...,...,...,...,...,...,...,...
116,2117,52.0,288791.0,8.0,11252.0,7.0,7.0,Annual,Port Harcourt,0
117,2118,45.0,210429.0,4.0,36972.0,5.0,9.0,Monthly,Lagos,0
118,2119,60.0,282206.0,4.0,34181.0,2.0,4.0,Annual,Port Harcourt,0
119,2120,21.0,324820.0,56.0,6944.0,1.0,7.0,Quarterly,Lagos,0
121,2100,60.0,412782.0,51.0,32476.0,0.0,10.0,Monthly,Lagos,0

In [40]:
print("Number of duplicate rows:", df.duplicated().sum())
df[df.duplicated(keep=False)].sort_values("customer_id")

Number of duplicate rows: 2

,customer_id,age,annual_income,tenure_months,monthly_spend,support_calls,orders_last_6_months,contract_type,region,churn
2,2003,44.0,143257.0,15.0,32210.0,4.0,8.0,Quarterly,Lagos,0
120,2003,44.0,143257.0,15.0,32210.0,4.0,8.0,Quarterly,Lagos,0
99,2100,60.0,412782.0,51.0,32476.0,0.0,10.0,Monthly,Lagos,0
121,2100,60.0,412782.0,51.0,32476.0,0.0,10.0,Monthly,Lagos,0

In [41]:
df = df.drop_duplicates()
print("Number of duplicate rows after cleaning:", df.duplicated().sum())

Number of duplicate rows after cleaning: 0

In [42]:
print("Missing Values:")
display(df.isnull().sum())

print("Duplicate rows:", df.duplicated().sum())
print("Negative ages:", (df["age"] < 0).sum())
print("Negayive support calls:", (df["support_calls"] < 0).sum())

print("\nRegions:")
display(df["region"].value_counts())

Missing Values:

customer_id             0
age                     0
annual_income           0
tenure_months           0
monthly_spend           0
support_calls           0
orders_last_6_months    0
contract_type           0
region                  0
churn                   0
dtype: int64

Duplicate rows: 0
Negative ages: 0
Negayive support calls: 0

Regions:

region
Lagos            37
Port Harcourt    27
Enugu            27
Abuja            18
Ibadan           11
Name: count, dtype: Int64

In [43]:
df.to_csv("ecommerce_churn_cleaned.csv", index=False)
print("saved: ", "ecommerce_churn_cleaned.csv")
print("Final shape: ", df.shape)

saved:  ecommerce_churn_cleaned.csv
Final shape:  (120, 10)